services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend-app:
    build: .
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PORT: 3000
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/prisma
      - /app/dist
    command: sh -c 'npm run start:prod'

  prisma-studio:
    build: .
    command: sh -c "npx prisma studio --port 5555"
    ports:
      - '5555:5555'
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  postgres-data:
